name: CI-CD Pipeline
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Backend/requirements.txt
          pip install pytest  # Ajout explicite pour garantir pytest
      - name: Run backend tests
        run: |
          pytest Backend/tests/test_pipelinedata.py
      - name: Run preprocessing
        run: |
          python Backend/pipelinedata.py

  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install frontend dependencies
        working-directory: ./mon-app
        run: npm install
      - name: Run frontend tests
        working-directory: ./mon-app
        run: npm test -- --watchAll=false