name: CI/CD Pipeline

on:
  push:
    branches:
      - master # Changed from main to master
  pull_request:
    branches:
      - master # Changed from main to master

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Or your preferred OS, usually ubuntu-latest for GitHub Actions

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        # Setting Python version to 3.11 as seen in your CI logs for pytest.
        python-version: '3.11' 

    - name: Install dependencies
      # Assuming requirements.txt is located inside the Backend directory
      run: pip install -r Backend/requirements.txt

    - name: Run tests
      # This step explicitly adds the 'Backend' directory to Python's import path.
      # This ensures 'models.pipelines.pipelinedata' can be found correctly
      # even when pytest is invoked with a path relative to the repo root.
      run: |
        export PYTHONPATH=$PYTHONPATH:./Backend
        pytest Backend/tests/test_pipelinedata.py
